// This function now directly returns a hardcoded list of schemes.
// This ensures that your application will always have data to display.

export const fetchAllSchemes = async () => {
  // We are returning a promise to simulate a real API call
  return new Promise(resolve => {
    setTimeout(() => { // Simulate network delay
      resolve([ // The array starts here, inside the resolve() function
        {
          "id": 1,
          "name_en": "PM Kisan Samman Nidhi",
          "name_hi": "पीएम किसान सम्मान निधि",
          "category": "Farmer",
          "summary_en": "Financial support of ₹6,000 per year for small and marginal farmers.",
          "summary_hi": "छोटे और सीमांत किसानों के लिए प्रति वर्ष ₹6,000 की वित्तीय सहायता।",
          "eligibility_en": "All landholding farmer families with cultivable land.",
          "eligibility_hi": "खेती योग्य भूमि वाले सभी भूमिधारक किसान परिवार।",
          "benefits_en": "₹2,000 every 4 months, directly to the bank account.",
          "benefits_hi": "हर 4 महीने में ₹2,000, सीधे बैंक खाते में।",
          "documents": ["Aadhaar Card", "Landholding papers", "Bank Account Passbook"],
          "officialLink": "https://pmkisan.gov.in/"
        },
        {
          "id": 2,
          "name_en": "Pradhan Mantri Jan Dhan Yojana (PMJDY)",
          "name_hi": "प्रधानमंत्री जन धन योजना (पीएमजेडीवाई)",
          "category": "Social Security",
          "summary_en": "National Mission for Financial Inclusion to ensure access to financial services.",
          "summary_hi": "वित्तीय सेवाओं तक पहुंच सुनिश्चित करने के लिए वित्तीय समावेशन के लिए राष्ट्रीय मिशन।",
          "eligibility_en": "Any Indian citizen above the age of 10 years without a bank account.",
          "eligibility_hi": "10 वर्ष से अधिक आयु का कोई भी भारतीय नागरिक जिसका बैंक खाता नहीं है।",
          "benefits_en": "Zero balance bank account, RuPay debit card, accident insurance cover of ₹2 lakh.",
          "benefits_hi": "जीरो बैलेंस बैंक खाता, रुपे डेबिट कार्ड, ₹2 लाख का दुर्घटना बीमा कवर।",
          "documents": ["Aadhaar Card", "Passport size photograph", "Address Proof"],
          "officialLink": "https://www.pmjdy.gov.in/"
        },
        {
          "id": 3,
          "name_en": "Sukanya Samriddhi Yojana (SSY)",
          "name_hi": "सुकन्या समृद्धि योजना (एसएसवाई)",
          "category": "Women & Children",
          "summary_en": "A small savings scheme for the girl child as part of 'Beti Bachao Beti Padhao' campaign.",
          "summary_hi": "'बेटी बचाओ बेटी पढ़ाओ' अभियान के तहत बालिका के लिए एक छोटी बचत योजना।",
          "eligibility_en": "Parents or legal guardians of a girl child below the age of 10.",
          "eligibility_hi": "10 वर्ष से कम उम्र की बालिका के माता-पिता या कानूनी अभिभावक।",
          "benefits_en": "High interest rate, tax benefits under section 80C. Account matures after 21 years.",
          "benefits_hi": "उच्च ब्याज दर, धारा 80सी के तहत कर लाभ। खाता 21 साल बाद परिपक्व होता है।",
          "documents": ["Birth certificate of the girl child", "Identity and address proof of the guardian", "Photograph of child and guardian"],
          "officialLink": "https://www.indiapost.gov.in/Financial/Pages/Content/sukanya-samriddhi-yojana.aspx"
        },
        {
            "id": 4,
            "name_en": "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
            "name_hi": "प्रधानमंत्री फसल बीमा योजना (पीएमएफबीवाई)",
            "category": "Farmer",
            "summary_en": "An insurance service for farmers for their yields against natural calamities.",
            "summary_hi": "प्राकृतिक आपदाओं के खिलाफ किसानों को उनकी उपज के लिए एक बीमा सेवा।",
            "eligibility_en": "All farmers including sharecroppers and tenant farmers growing notified crops in notified areas.",
            "eligibility_hi": "बटाईदारों और काश्तकार किसानों सहित सभी किसान जो अधिसूचित क्षेत्रों में अधिसूचित फसलें उगा रहे हैं।",
            "benefits_en": "Insurance coverage against crop failure due to natural calamities, pests & diseases.",
            "benefits_hi": "प्राकृतिक आपदाओं, कीटों और रोगों के कारण फसल खराब होने पर बीमा कवरेज।",
            "documents": ["Land records (Khasra Patwari)", "Aadhaar card", "Bank passbook", "Sowing Declaration Form"],
            "officialLink": "https://pmfby.gov.in/"
        },
        {
            "id": 5,
            "name_en": "Ayushman Bharat Pradhan Mantri Jan Arogya Yojana (AB-PMJAY)",
            "name_hi": "आयुष्मान भारत प्रधानमंत्री जन आरोग्य योजना (एबी-पीएमजेएवाई)",
            "category": "Health",
            "summary_en": "Provides a health insurance cover of up to ₹5 lakh per family per year for secondary and tertiary care hospitalization.",
            "summary_hi": "माध्यमिक और तृतीयक देखभाल अस्पताल में भर्ती के लिए प्रति परिवार प्रति वर्ष ₹5 लाख तक का स्वास्थ्य बीमा कवर प्रदान करता है।",
            "eligibility_en": "Based on the socio-economic caste census (SECC) 2011 data, covering poor and vulnerable families.",
            "eligibility_hi": "सामाजिक-आर्थिक जाति जनगणना (SECC) 2011 के आंकड़ों के आधार पर, गरीब और कमजोर परिवारों को कवर करता है।",
            "benefits_en": "Cashless hospitalization, covers pre and post-hospitalization expenses, access to public and private empanelled hospitals.",
            "benefits_hi": "कैशलेस अस्पताल में भर्ती, अस्पताल में भर्ती होने से पहले और बाद के खर्चों को कवर करता है, सार्वजनिक और निजी पैनलबद्ध अस्पतालों तक पहुंच।",
            "documents": ["Aadhaar Card", "Ration Card", "PM Letter / PMJAY Card"],
            "officialLink": "https://pmjay.gov.in/"
        },
        {
        "id": 6,
        "name_en": "Pradhan Mantri Awas Yojana - Urban (PMAY-U)",
        "name_hi": "प्रधानमंत्री आवास योजना - शहरी (पीएमएवाई-यू)",
        "category": "Housing",
        "summary_en": "A mission to provide affordable housing for all in urban areas by the year 2022.",
        "summary_hi": "वर्ष 2022 तक शहरी क्षेत्रों में सभी के लिए किफायती आवास उपलब्ध कराने का एक मिशन।",
        "eligibility_en": "Economically Weaker Section (EWS), Low Income Group (LIG), and Middle Income Group (MIG). The beneficiary family should not own a pucca house.",
        "eligibility_hi": "आर्थिक रूप से कमजोर वर्ग (EWS), निम्न आय वर्ग (LIG), और मध्यम आय वर्ग (MIG)। लाभार्थी परिवार के पास पक्का घर नहीं होना चाहिए।",
        "benefits_en": "Credit-linked subsidy on home loans, financial assistance for construction or enhancement of a house.",
        "benefits_hi": "होम लोन पर क्रेडिट-लिंक्ड सब्सिडी, घर के निर्माण या वृद्धि के लिए वित्तीय सहायता।",
        "documents": ["Aadhaar Card", "Income Certificate", "Proof of Residence", "Affidavit stating no pucca house ownership"],
        "officialLink": "https://pmay-urban.gov.in/"
    },
    {
        "id": 7,
        "name_en": "Pradhan Mantri Awas Yojana - Gramin (PMAY-G)",
        "name_hi": "प्रधानमंत्री आवास योजना - ग्रामीण (पीएमएवाई-जी)",
        "category": "Housing",
        "summary_en": "Aims to provide a pucca house with basic amenities to all homeless households and households living in kutcha and dilapidated houses in rural areas.",
        "summary_hi": "ग्रामीण क्षेत्रों में सभी बेघर परिवारों और कच्चे और जीर्ण-शीर्ण घरों में रहने वाले परिवारों को बुनियादी सुविधाओं के साथ एक पक्का घर प्रदान करना है।",
        "eligibility_en": "Homeless families or families living in kutcha houses, based on SECC 2011 data and verified by Gram Sabhas.",
        "eligibility_hi": "SECC 2011 के आंकड़ों के आधार पर और ग्राम सभाओं द्वारा सत्यापित बेघर परिवार या कच्चे घरों में रहने वाले परिवार।",
        "benefits_en": "Financial assistance for construction of the house, linkage with other government schemes.",
        "benefits_hi": "घर के निर्माण के लिए वित्तीय सहायता, अन्य सरकारी योजनाओं के साथ जुड़ाव।",
        "documents": ["Aadhaar Card", "Job card of MGNREGA beneficiary", "Bank account details"],
        "officialLink": "https://pmayg.nic.in/"
    },
    {
        "id": 8,
        "name_en": "National Pension System (NPS)",
        "name_hi": "राष्ट्रीय पेंशन प्रणाली (एनपीएस)",
        "category": "Social Security & Pension",
        "summary_en": "A voluntary, defined contribution retirement savings scheme designed to enable systematic savings during the working life.",
        "summary_hi": "एक स्वैच्छिक, परिभाषित अंशदान सेवानिवृत्ति बचत योजना जो कामकाजी जीवन के दौरान व्यवस्थित बचत को सक्षम करने के लिए डिज़ाइन की गई है।",
        "eligibility_en": "Any Indian citizen between 18 and 70 years of age.",
        "eligibility_hi": "18 से 70 वर्ष की आयु के बीच का कोई भी भारतीय नागरिक।",
        "benefits_en": "Provides a pension post-retirement, offers tax benefits, portable across jobs and locations.",
        "benefits_hi": "सेवानिवृत्ति के बाद पेंशन प्रदान करता है, कर लाभ प्रदान करता है, नौकरियों और स्थानों पर पोर्टेबल है।",
        "documents": ["Aadhaar Card", "PAN Card", "Bank Account Details", "Photograph"],
        "officialLink": "https://www.npscra.nsdl.co.in/"
    },
    {
        "id": 9,
        "name_en": "Atal Pension Yojana (APY)",
        "name_hi": "अटल पेंशन योजना (एपीवाई)",
        "category": "Social Security & Pension",
        "summary_en": "A pension scheme focused on the unorganized sector workers.",
        "summary_hi": "असंगठित क्षेत्र के श्रमिकों पर केंद्रित एक पेंशन योजना।",
        "eligibility_en": "Any Indian citizen between 18 and 40 years of age with a bank account. Must not be a member of any statutory social security scheme.",
        "eligibility_hi": "18 से 40 वर्ष की आयु का कोई भी भारतीय नागरिक जिसका बैंक खाता हो। किसी भी वैधानिक सामाजिक सुरक्षा योजना का सदस्य नहीं होना चाहिए।",
        "benefits_en": "Guaranteed minimum monthly pension of ₹1000, ₹2000, ₹3000, ₹4000, or ₹5000 at the age of 60.",
        "benefits_hi": "60 वर्ष की आयु में ₹1000, ₹2000, ₹3000, ₹4000, या ₹5000 की गारंटीकृत न्यूनतम मासिक पेंशन।",
        "documents": ["Aadhaar Card", "Bank Account Details"],
        "officialLink": "https://www.npscra.nsdl.co.in/scheme-details.php"
    },
    {
        "id": 10,
        "name_en": "Pradhan Mantri Suraksha Bima Yojana (PMSBY)",
        "name_hi": "प्रधानमंत्री सुरक्षा बीमा योजना (पीएमएसबीवाई)",
        "category": "Social Security",
        "summary_en": "An accident insurance scheme offering death and disability cover for death or disability on account of an accident.",
        "summary_hi": "एक दुर्घटना बीमा योजना जो दुर्घटना के कारण मृत्यु या विकलांगता के लिए मृत्यु और विकलांगता कवर प्रदान करती है।",
        "eligibility_en": "Any person between 18 and 70 years of age with a bank account.",
        "eligibility_hi": "18 से 70 वर्ष की आयु का कोई भी व्यक्ति जिसका बैंक खाता हो।",
        "benefits_en": "₹2 Lakh for accidental death and full disability, ₹1 Lakh for partial disability. Premium is ₹20 per year.",
        "benefits_hi": "आकस्मिक मृत्यु और पूर्ण विकलांगता के लिए ₹2 लाख, आंशिक विकलांगता के लिए ₹1 लाख। प्रीमियम ₹20 प्रति वर्ष है।",
        "documents": ["Aadhaar Card linked to bank account"],
        "officialLink": "https://www.jansuraksha.gov.in/"
    },
    {
        "id": 11,
        "name_en": "Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)",
        "name_hi": "प्रधानमंत्री जीवन ज्योति बीमा योजना (पीएमजेजेबीवाई)",
        "category": "Social Security",
        "summary_en": "A life insurance scheme offering coverage for death due to any reason.",
        "summary_hi": "एक जीवन बीमा योजना जो किसी भी कारण से मृत्यु के लिए कवरेज प्रदान करती है।",
        "eligibility_en": "Any person between 18 and 50 years of age with a bank account.",
        "eligibility_hi": "18 से 50 वर्ष की आयु का कोई भी व्यक्ति जिसका बैंक खाता हो।",
        "benefits_en": "Life insurance cover of ₹2 Lakh. Premium is ₹436 per year.",
        "benefits_hi": "₹2 लाख का जीवन बीमा कवर। प्रीमियम ₹436 प्रति वर्ष है।",
        "documents": ["Aadhaar Card linked to bank account"],
        "officialLink": "https://www.jansuraksha.gov.in/"
    },
    {
        "id": 12,
        "name_en": "Pradhan Mantri Ujjwala Yojana (PMUY)",
        "name_hi": "प्रधानमंत्री उज्ज्वला योजना (पीएमयूवाई)",
        "category": "Women & Children",
        "summary_en": "Aims to provide LPG connections to women from Below Poverty Line (BPL) households.",
        "summary_hi": "गरीबी रेखा से नीचे (बीपीएल) के परिवारों की महिलाओं को एलपीजी कनेक्शन प्रदान करना।",
        "eligibility_en": "Adult woman belonging to a poor household and not having an LPG connection in her household.",
        "eligibility_hi": "एक गरीब परिवार से संबंधित वयस्क महिला और जिसके घर में एलपीजी कनेक्शन नहीं है।",
        "benefits_en": "Deposit-free LPG connection with financial assistance of ₹1600 per connection.",
        "benefits_hi": "प्रति कनेक्शन ₹1600 की वित्तीय सहायता के साथ जमा-मुक्त एलपीजी कनेक्शन।",
        "documents": ["Aadhaar Card", "BPL Ration Card", "Bank Account Details", "KYC Form"],
        "officialLink": "https://www.pmuy.gov.in/"
    },
    {
        "id": 13,
        "name_en": "Stand-Up India Scheme",
        "name_hi": "स्टैंड-अप इंडिया योजना",
        "category": "MSME & Entrepreneurs",
        "summary_en": "Facilitates bank loans between ₹10 lakh and ₹1 Crore to at least one Scheduled Caste (SC) or Scheduled Tribe (ST) borrower and at least one woman borrower per bank branch for setting up a greenfield enterprise.",
        "summary_hi": "एक ग्रीनफील्ड उद्यम स्थापित करने के लिए प्रति बैंक शाखा कम से कम एक अनुसूचित जाति (एससी) या अनुसूचित जनजाति (एसटी) उधारकर्ता और कम से कम एक महिला उधारकर्ता को ₹10 लाख से ₹1 करोड़ के बीच बैंक ऋण की सुविधा प्रदान करता है।",
        "eligibility_en": "SC/ST and/or women entrepreneurs, above 18 years of age. For setting up a new enterprise in manufacturing, services or the trading sector.",
        "eligibility_hi": "एससी/एसटी और/या महिला उद्यमी, 18 वर्ष से अधिक आयु के। विनिर्माण, सेवाओं या व्यापार क्षेत्र में एक नया उद्यम स्थापित करने के लिए।",
        "benefits_en": "Composite loan (including term loan and working capital) between ₹10 lakh and ₹1 crore.",
        "benefits_hi": "₹10 लाख से ₹1 करोड़ के बीच समग्र ऋण (सावधि ऋण और कार्यशील पूंजी सहित)।",
        "documents": ["Identity Proof", "Address Proof", "Business Address Proof", "Project Report"],
        "officialLink": "https://www.standupmitra.in/"
    },
    {
        "id": 14,
        "name_en": "Pradhan Mantri Mudra Yojana (PMMY)",
        "name_hi": "प्रधानमंत्री मुद्रा योजना (पीएमएमवाई)",
        "category": "MSME & Entrepreneurs",
        "summary_en": "Provides loans up to ₹10 lakh to non-corporate, non-farm small/micro enterprises.",
        "summary_hi": "गैर-कॉर्पोरेट, गैर-कृषि लघु/सूक्ष्म उद्यमों को ₹10 लाख तक का ऋण प्रदान करता है।",
        "eligibility_en": "Any Indian Citizen who has a business plan for a non-farm sector income-generating activity such as manufacturing, processing, trading or service sector.",
        "eligibility_hi": "कोई भी भारतीय नागरिक जिसके पास गैर-कृषि क्षेत्र की आय-सृजन गतिविधि जैसे विनिर्माण, प्रसंस्करण, व्यापार या सेवा क्षेत्र के लिए एक व्यावसायिक योजना है।",
        "benefits_en": "Loans are given in three categories: Shishu (up to ₹50,000), Kishor (₹50,001 to ₹5 lakh), and Tarun (₹5,00,001 to ₹10 lakh). No collateral needed.",
        "benefits_hi": "ऋण तीन श्रेणियों में दिए जाते हैं: शिशु (₹50,000 तक), किशोर (₹50,001 से ₹5 लाख), और तरुण (₹5,00,001 से ₹10 लाख)। किसी संपार्श्विक की आवश्यकता नहीं है।",
        "documents": ["Business Plan", "KYC Documents (Aadhaar, PAN)", "Application Form"],
        "officialLink": "https://www.mudra.org.in/"
    },
    {
        "id": 15,
        "name_en": "National Scholarship Portal (NSP)",
        "name_hi": "राष्ट्रीय छात्रवृत्ति पोर्टल (एनएसपी)",
        "category": "Youth & Students",
        "summary_en": "A one-stop platform for students to apply for various scholarship schemes offered by Central Government, State Governments, and UGC.",
        "summary_hi": "केंद्र सरकार, राज्य सरकारों और यूजीसी द्वारा दी जाने वाली विभिन्न छात्रवृत्ति योजनाओं के लिए आवेदन करने के लिए छात्रों के लिए एक वन-स्टॉप प्लेटफॉर्म।",
        "eligibility_en": "Varies by scheme. Open to students from primary school to postgraduate level, based on academic merit and financial need.",
        "eligibility_hi": "योजना के अनुसार भिन्न होता है। प्राथमिक विद्यालय से स्नातकोत्तर स्तर तक के छात्रों के लिए खुला है, जो अकादमिक योग्यता और वित्तीय आवश्यकता पर आधारित है।",
        "benefits_en": "Financial assistance for education, covering tuition fees, maintenance allowance, etc.",
        "benefits_hi": "शिक्षा के लिए वित्तीय सहायता, ट्यूशन फीस, रखरखाव भत्ता आदि को कवर करना।",
        "documents": ["Aadhaar Card", "Educational Documents", "Bank Passbook", "Caste/Income Certificate (if applicable)"],
        "officialLink": "https://scholarships.gov.in/"
    },
    {
        "id": 16,
        "name_en": "Pradhan Mantri Kaushal Vikas Yojana (PMKVY)",
        "name_hi": "प्रधानमंत्री कौशल विकास योजना (पीएमकेवीवाई)",
        "category": "Youth & Students",
        "summary_en": "Aims to enable a large number of Indian youth to take up industry-relevant skill training that will help them in securing a better livelihood.",
        "summary_hi": "इसका उद्देश्य बड़ी संख्या में भारतीय युवाओं को उद्योग-प्रासंगिक कौशल प्रशिक्षण लेने में सक्षम बनाना है जो उन्हें बेहतर आजीविका हासिल करने में मदद करेगा।",
        "eligibility_en": "Any Indian national who is unemployed or school/college dropout.",
        "eligibility_hi": "कोई भी भारतीय नागरिक जो बेरोजगार या स्कूल/कॉलेज ड्रॉपआउट है।",
        "benefits_en": "Free short-duration skill training, monetary reward upon successful assessment and certification, placement assistance.",
        "benefits_hi": "नि:शुल्क अल्पकालिक कौशल प्रशिक्षण, सफल मूल्यांकन और प्रमाणन पर मौद्रिक पुरस्कार, प्लेसमेंट सहायता।",
        "documents": ["Aadhaar Card", "Bank Account Details", "Two passport size photographs"],
        "officialLink": "https://www.pmkvyofficial.org/"
    },
    {
        "id": 17,
        "name_en": "Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)",
        "name_hi": "महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी अधिनियम (मनरेगा)",
        "category": "Social Security",
        "summary_en": "Guarantees the 'right to work' and aims to enhance livelihood security in rural areas by providing at least 100 days of wage employment in a financial year.",
        "summary_hi": "एक वित्तीय वर्ष में कम से कम 100 दिनों का मजदूरी रोजगार प्रदान करके 'काम के अधिकार' की गारंटी देता है और ग्रामीण क्षेत्रों में आजीविका सुरक्षा को बढ़ाता है।",
        "eligibility_en": "Every adult member of a rural household who volunteers to do unskilled manual work.",
        "eligibility_hi": "एक ग्रामीण परिवार का प्रत्येक वयस्क सदस्य जो अकुशल शारीरिक काम करने के लिए स्वेच्छा से काम करता है।",
        "benefits_en": "Legal guarantee of 100 days of employment, wages paid directly to bank accounts, creation of durable assets in rural areas.",
        "benefits_hi": "100 दिनों के रोजगार की कानूनी गारंटी, मजदूरी सीधे बैंक खातों में भुगतान, ग्रामीण क्षेत्रों में टिकाऊ संपत्ति का निर्माण।",
        "documents": ["Job Card (issued by Gram Panchayat)", "Aadhaar Card", "Bank Account Details"],
        "officialLink": "https://nrega.nic.in/"
    },
    {
        "id": 18,
        "name_en": "Pradhan Mantri Matru Vandana Yojana (PMMVY)",
        "name_hi": "प्रधानमंत्री मातृ वंदना योजना (पीएमएमवीवाई)",
        "category": "Women & Children",
        "summary_en": "A maternity benefit program that provides partial wage compensation to women for wage-loss during childbirth and childcare.",
        "summary_hi": "एक मातृत्व लाभ कार्यक्रम जो महिलाओं को प्रसव और बच्चे की देखभाल के दौरान मजदूरी-हानि के लिए आंशिक मजदूरी मुआवजा प्रदान करता है।",
        "eligibility_en": "Pregnant and lactating women for the first live birth.",
        "eligibility_hi": "पहले जीवित जन्म के लिए गर्भवती और स्तनपान कराने वाली महिलाएं।",
        "benefits_en": "Cash incentive of ₹5,000 in three installments.",
        "benefits_hi": "तीन किश्तों में ₹5,000 का नकद प्रोत्साहन।",
        "documents": ["MCP Card (Mother and Child Protection)", "Aadhaar Card of beneficiary and her husband", "Bank Account Details"],
        "officialLink": "https://pmmvy.wcd.nic.in/"
    },
    {
        "id": 19,
        "name_en": "Kisan Credit Card (KCC) Scheme",
        "name_hi": "किसान क्रेडिट कार्ड (केसीसी) योजना",
        "category": "Farmer",
        "summary_en": "Provides farmers with timely access to credit for their cultivation and other needs.",
        "summary_hi": "किसानों को उनकी खेती और अन्य जरूरतों के लिए समय पर ऋण उपलब्ध कराता है।",
        "eligibility_en": "All farmers - individuals/joint borrowers who are owner cultivators; tenant farmers, oral lessees & sharecroppers.",
        "eligibility_hi": "सभी किसान - व्यक्ति/संयुक्त उधारकर्ता जो मालिक किसान हैं; काश्तकार किसान, मौखिक पट्टेदार और बटाईदार।",
        "benefits_en": "Revolving credit facility, flexible repayment, low interest rates (with government interest subvention).",
        "benefits_hi": "परिक्रामी ऋण सुविधा, लचीला पुनर्भुगतान, कम ब्याज दरें (सरकारी ब्याज सबवेंशन के साथ)।",
        "documents": ["Land documents", "Identity Proof (Aadhaar, PAN)", "Address Proof", "Photograph"],
        "officialLink": "https://www.sbi.co.in/web/agri-rural/agriculture-banking/crop-finance/kisan-credit-card"
    },
    {
        "id": 20,
        "name_en": "National Food Security Mission (NFSM)",
        "name_hi": "राष्ट्रीय खाद्य सुरक्षा मिशन (एनएफएसएम)",
        "category": "Farmer",
        "summary_en": "Aims to increase the production of rice, wheat, pulses, coarse cereals, and commercial crops through area expansion and productivity enhancement.",
        "summary_hi": "क्षेत्र विस्तार और उत्पादकता वृद्धि के माध्यम से चावल, गेहूं, दालें, मोटे अनाज और वाणिज्यिक फसलों का उत्पादन बढ़ाना है।",
        "eligibility_en": "Farmers across specified districts in India.",
        "eligibility_hi": "भारत के निर्दिष्ट जिलों के किसान।",
        "benefits_en": "Subsidies on seeds, farm machinery, soil management, and integrated pest management.",
        "benefits_hi": "बीज, कृषि मशीनरी, मिट्टी प्रबंधन और एकीकृत कीट प्रबंधन पर सब्सिडी।",
        "documents": ["Farmer registration", "Land records"],
        "officialLink": "https://www.nfsm.gov.in/"
    },
    {
        "id": 21,
        "name_en": "Pradhan Mantri Kisan Maan-Dhan Yojana (PM-KMY)",
        "name_hi": "प्रधानमंत्री किसान मान-धन योजना (पीएम-केएमवाई)",
        "category": "Farmer",
        "summary_en": "A voluntary and contributory pension scheme for small and marginal farmers.",
        "summary_hi": "छोटे और सीमांत किसानों के लिए एक स्वैच्छिक और अंशदायी पेंशन योजना।",
        "eligibility_en": "Small and Marginal Farmers (SMFs) who have cultivable land up to 2 hectares and are between 18 to 40 years of age.",
        "eligibility_hi": "छोटे और सीमांत किसान (एसएमएफ) जिनके पास 2 हेक्टेयर तक खेती योग्य भूमि है और वे 18 से 40 वर्ष की आयु के बीच हैं।",
        "benefits_en": "Provides a minimum fixed pension of ₹3,000 per month on attaining the age of 60 years.",
        "benefits_hi": "60 वर्ष की आयु प्राप्त करने पर प्रति माह ₹3,000 की न्यूनतम निश्चित पेंशन प्रदान करता है।",
        "documents": ["Aadhaar Card", "Bank Account Passbook"],
        "officialLink": "https://maandhan.in/"
    },
    {
        "id": 22,
        "name_en": "Mission for Integrated Development of Horticulture (MIDH)",
        "name_hi": "बागवानी के एकीकृत विकास के लिए मिशन (एमआईडीएच)",
        "category": "Farmer",
        "summary_en": "Promotes the holistic growth of the horticulture sector, including fruits, vegetables, and flowers.",
        "summary_hi": "फल, सब्जियां और फूलों सहित बागवानी क्षेत्र के समग्र विकास को बढ़ावा देता है।",
        "eligibility_en": "Farmers, farmer producer organizations (FPOs), entrepreneurs.",
        "eligibility_hi": "किसान, किसान उत्पादक संगठन (एफपीओ), उद्यमी।",
        "benefits_en": "Financial assistance for setting up nurseries, establishing new gardens, water resource development, and post-harvest management.",
        "benefits_hi": "नर्सरी स्थापित करने, नए बाग लगाने, जल संसाधन विकास और कटाई के बाद के प्रबंधन के लिए वित्तीय सहायता।",
        "documents": ["Project proposal", "Land documents", "Farmer ID"],
        "officialLink": "https://midh.gov.in/"
    },
    {
        "id": 23,
        "name_en": "e-NAM (National Agriculture Market)",
        "name_hi": "ई-नाम (राष्ट्रीय कृषि बाजार)",
        "category": "Farmer",
        "summary_en": "A pan-India electronic trading portal which networks the existing APMC mandis to create a unified national market for agricultural commodities.",
        "summary_hi": "एक अखिल भारतीय इलेक्ट्रॉनिक ट्रेडिंग पोर्टल जो कृषि जिंसों के लिए एक एकीकृत राष्ट्रीय बाजार बनाने के लिए मौजूदा एपीएमसी मंडियों को नेटवर्क करता है।",
        "eligibility_en": "Farmers, traders, and buyers registered with APMC.",
        "eligibility_hi": "एपीएमसी के साथ पंजीकृत किसान, व्यापारी और खरीदार।",
        "benefits_en": "Transparent online trading, real-time price discovery, better returns for farmers, access to a larger market.",
        "benefits_hi": "पारदर्शी ऑनलाइन ट्रेडिंग, वास्तविक समय में मूल्य खोज, किसानों के लिए बेहतर रिटर्न, एक बड़े बाजार तक पहुंच।",
        "documents": ["Aadhaar card", "Bank Passbook", "Trader License (for traders)"],
        "officialLink": "https://www.enam.gov.in/"
    },
    {
        "id": 24,
        "name_en": "Soil Health Card Scheme",
        "name_hi": "मृदा स्वास्थ्य कार्ड योजना",
        "category": "Farmer",
        "summary_en": "A scheme to issue Soil Health Cards to farmers every 2 years to provide a basis for addressing nutritional deficiencies in the soil.",
        "summary_hi": "मिट्टी में पोषण संबंधी कमियों को दूर करने के लिए एक आधार प्रदान करने के लिए हर 2 साल में किसानों को मृदा स्वास्थ्य कार्ड जारी करने की एक योजना।",
        "eligibility_en": "All farmers in the country.",
        "eligibility_hi": "देश के सभी किसान।",
        "benefits_en": "Provides crop-wise recommendations of nutrients and fertilizers required, helps in increasing crop yields and soil health.",
        "benefits_hi": "आवश्यक पोषक तत्वों और उर्वरकों की फसल-वार सिफारिशें प्रदान करता है, फसल की पैदावार और मिट्टी के स्वास्थ्य को बढ़ाने में मदद करता है।",
        "documents": ["Farmer details collected by state agriculture departments"],
        "officialLink": "https://soilhealth.dac.gov.in/"
    },
    {
        "id": 25,
        "name_en": "National AYUSH Mission (NAM)",
        "name_hi": "राष्ट्रीय आयुष मिशन (नाम)",
        "category": "Health",
        "summary_en": "Aims to promote AYUSH medical systems through cost-effective services, strengthening educational systems, and facilitating the enforcement of quality control.",
        "summary_hi": "लागत प्रभावी सेवाओं के माध्यम से आयुष चिकित्सा प्रणालियों को बढ़ावा देना, शैक्षिक प्रणालियों को मजबूत करना और गुणवत्ता नियंत्रण के प्रवर्तन को सुगम बनाना है।",
        "eligibility_en": "All citizens, with services provided through AYUSH hospitals and dispensaries.",
        "eligibility_hi": "सभी नागरिक, आयुष अस्पतालों और औषधालयों के माध्यम से प्रदान की जाने वाली सेवाओं के साथ।",
        "benefits_en": "Access to traditional medicine (Ayurveda, Yoga, Unani, Siddha, Homeopathy), grants for upgrading AYUSH facilities.",
        "benefits_hi": "पारंपरिक चिकित्सा तक पहुंच (आयुर्वेद, योग, यूनानी, सिद्ध, होम्योपैथी), आयुष सुविधाओं के उन्नयन के लिए अनुदान।",
        "documents": ["Generally not required for consultation; scheme-specific for other benefits"],
        "officialLink": "https://www.ayush.gov.in/"
    },
    {
        "id": 26,
        "name_en": "Pradhan Mantri Bhartiya Janaushadhi Pariyojana (PMBJP)",
        "name_hi": "प्रधानमंत्री भारतीय जनऔषधि परियोजना (पीएमबीजेपी)",
        "category": "Health",
        "summary_en": "A campaign to provide quality medicines at affordable prices to the masses through dedicated outlets known as Pradhan Mantri Bhartiya Janaushadhi Kendras.",
        "summary_hi": "प्रधानमंत्री भारतीय जनऔषधि केंद्रों के नाम से जाने जाने वाले समर्पित आउटलेट के माध्यम से जनता को सस्ती कीमतों पर गुणवत्तापूर्ण दवाएं उपलब्ध कराने का एक अभियान।",
        "eligibility_en": "All citizens of India.",
        "eligibility_hi": "भारत के सभी नागरिक।",
        "benefits_en": "Availability of generic medicines at lower prices, reducing out-of-pocket expenditure on healthcare.",
        "benefits_hi": "कम कीमतों पर जेनेरिक दवाओं की उपलब्धता, स्वास्थ्य सेवा पर जेब से होने वाले खर्च को कम करना।",
        "documents": ["Doctor's prescription for purchasing medicines"],
        "officialLink": "http://janaushadhi.gov.in/"
    },
    {
        "id": 27,
        "name_en": "Vande Bharat Mission",
        "name_hi": "वंदे भारत मिशन",
        "category": "Social Security",
        "summary_en": "One of the largest civilian evacuation exercises to bring back Indian citizens stranded abroad amidst the coronavirus pandemic.",
        "summary_hi": "कोरोनावायरस महामारी के बीच विदेश में फंसे भारतीय नागरिकों को वापस लाने के लिए सबसे बड़े नागरिक निकासी अभ्यासों में से एक।",
        "eligibility_en": "Indian citizens stranded overseas with compelling reasons to return, such as job loss, visa expiry, or medical emergencies.",
        "eligibility_hi": "विदेश में फंसे भारतीय नागरिक जिनके पास लौटने के ठोस कारण हैं, जैसे नौकरी छूटना, वीजा समाप्त होना, या चिकित्सा आपात स्थिति।",
        "benefits_en": "Repatriation to India via special non-scheduled commercial flights, naval ships.",
        "benefits_hi": "विशेष गैर-अनुसूचित वाणिज्यिक उड़ानों, नौसेना के जहाजों के माध्यम से भारत प्रत्यावर्तन।",
        "documents": ["Valid Indian Passport", "Registration on the embassy portal"],
        "officialLink": "https://www.mea.gov.in/vande-bharat-mission.htm"
    },
    {
        "id": 28,
        "name_en": "Credit Guarantee Fund Scheme for Micro and Small Enterprises (CGS)",
        "name_hi": "सूक्ष्म और लघु उद्यमों के लिए क्रेडिट गारंटी फंड योजना (सीजीएस)",
        "category": "MSME & Entrepreneurs",
        "summary_en": "Provides collateral-free credit to the micro and small enterprise sector.",
        "summary_hi": "सूक्ष्म और लघु उद्यम क्षेत्र को संपार्श्विक-मुक्त ऋण प्रदान करता है।",
        "eligibility_en": "New and existing Micro and Small Enterprises (MSEs).",
        "eligibility_hi": "नए और मौजूदा सूक्ष्म और लघु उद्यम (एमएसई)।",
        "benefits_en": "Collateral-free loans up to ₹2 crore from banks and financial institutions.",
        "benefits_hi": "बैंकों और वित्तीय संस्थानों से ₹2 करोड़ तक का संपार्श्विक-मुक्त ऋण।",
        "documents": ["Business registration", "Project report", "KYC documents"],
        "officialLink": "https://www.cgtmse.in/"
    },
    {
        "id": 29,
        "name_en": "National Means Cum-Merit Scholarship Scheme (NMMSS)",
        "name_hi": "राष्ट्रीय मीन्स-कम-मेरिट छात्रवृत्ति योजना (एनएमएमएसएस)",
        "category": "Youth & Students",
        "summary_en": "A scholarship to award meritorious students of economically weaker sections to arrest their drop-out at class VIII and encourage them to continue their study.",
        "summary_hi": "आर्थिक रूप से कमजोर वर्गों के मेधावी छात्रों को कक्षा आठवीं में उनकी पढ़ाई छोड़ने से रोकने और उन्हें अपनी पढ़ाई जारी रखने के लिए प्रोत्साहित करने के लिए एक छात्रवृत्ति।",
        "eligibility_en": "Students studying in class IX, having secured at least 55% marks in Class VIII examination. Parental income should not exceed ₹3.5 lakh per annum.",
        "eligibility_hi": "कक्षा IX में पढ़ने वाले छात्र, जिन्होंने कक्षा VIII की परीक्षा में कम से कम 55% अंक प्राप्त किए हों। माता-पिता की आय प्रति वर्ष ₹3.5 लाख से अधिक नहीं होनी चाहिए।",
        "benefits_en": "Scholarship of ₹12,000 per annum.",
        "benefits_hi": "प्रति वर्ष ₹12,000 की छात्रवृत्ति।",
        "documents": ["Caste Certificate", "Income Certificate", "Class VIII Marksheet", "Aadhaar Card"],
        "officialLink": "https://scholarships.gov.in/"
    },
        {
            "id": 30,
            "name_en": "Beti Bachao, Beti Padhao Scheme",
            "name_hi": "बेटी बचाओ, बेटी पढ़ाओ योजना",
            "category": "Women & Children",
            "summary_en": "Aims to address the declining Child Sex Ratio (CSR) and related issues of women empowerment over a life-cycle continuum.",
            "summary_hi": "इसका उद्देश्य घटते बाल लिंगानुपात (सीएसआर) और जीवन-चक्र की निरंतरता पर महिला सशक्तिकरण के संबंधित मुद्दों का समाधान करना है।",
            "eligibility_en": "The scheme focuses on all Indian citizens, with a focus on districts with low child sex ratio.",
            "eligibility_hi": "यह योजना सभी भारतीय नागरिकों पर केंद्रित है, जिसमें कम बाल लिंगानुपात वाले जिलों पर ध्यान केंद्रित किया गया है।",
            "benefits_en": "Advocacy and awareness campaigns, improvement in sex ratio at birth, promoting girl's education. Financial component is primarily through Sukanya Samriddhi Yojana.",
            "benefits_hi": "वकालत और जागरूकता अभियान, जन्म के समय लिंगानुपात में सुधार, लड़की की शिक्षा को बढ़ावा देना। वित्तीय घटक मुख्य रूप से सुकन्या समृद्धि योजना के माध्यम से है।",
            "documents": ["Not applicable for general benefits, specific documents for linked schemes like SSY."],
            "officialLink": "https://wcd.nic.in/bbbp-schemes"
        }
      ]); // The array ends here
    }, 500); // 0.5 second delay
  });
};